src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $productName = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $ProductDescription = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $productPrice = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $productAlcoholLevel = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $productVolume = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $productColor = null;

    #[ORM\Column]
    private ?int $productStock = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'favoriteProducts')]
    private Collection $users;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?Type $type = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Vat $vat = null;

    /**
     * @var Collection<int, Picture>
     */
    #[ORM\OneToMany(targetEntity: Picture::class, mappedBy: 'product')]
    private Collection $pictures;

    #[ORM\Column(nullable: true)]
    private ?bool $isPermanent = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $productGender = null;

    #[ORM\Column]
    private ?bool $isDeleted = null;

    /**
    * @var Collection<int, OrderProducts>
    */
    #[ORM\OneToMany(targetEntity: OrderProduct::class, mappedBy: 'appProduct')]
    private Collection $orderProducts;

    #[ORM\ManyToOne(inversedBy: 'relation')]
    private ?Size $size = null;


    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->orderProducts = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductName(): ?string
    {
        return $this->productName;
    }

    public function setProductName(string $productName): static
    {
        $this->productName = $productName;

        return $this;
    }

    public function getProductDescription(): ?string
    {
        return $this->ProductDescription;
    }

    public function setProductDescription(?string $ProductDescription): static
    {
        $this->ProductDescription = $ProductDescription;

        return $this;
    }

    public function getProductPrice(): ?string
    {
        return $this->productPrice;
    }

    public function setProductPrice(string $productPrice): static
    {
        $this->productPrice = $productPrice;

        return $this;
    }

    public function getProductVATprice(): ?string
    {
        return $this->productVATprice;
    }

    public function setProductVATprice(string $productVATprice): static
    {
        $this->productVATprice = $productVATprice;

        return $this;
    }

    public function getProductAlcoholLevel(): ?string
    {
        return $this->productAlcoholLevel;
    }

    public function setProductAlcoholLevel(?string $productAlcoholLevel): static
    {
        $this->productAlcoholLevel = $productAlcoholLevel;

        return $this;
    }

    public function getProductVolume(): ?string
    {
        return $this->productVolume;
    }

    public function setProductVolume(?string $productVolume): static
    {
        $this->productVolume = $productVolume;

        return $this;
    }

    public function getProductColor(): ?string
    {
        return $this->productColor;
    }

    public function setProductColor(string $productColor): static
    {
        $this->productColor = $productColor;

        return $this;
    }

    public function getProductStock(): ?int
    {
        return $this->productStock;
    }

    public function setProductStock(int $productStock): static
    {
        $this->productStock = $productStock;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addFavoriteProduct($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            $user->removeProduct($this);
        }

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getVat(): ?Vat
    {
        return $this->vat;
    }

    public function setVat(?Vat $vat): static
    {
        $this->vat = $vat;

        return $this;
    }

    /**
     * @return Collection<int, Picture>
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): static
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures->add($picture);
            $picture->setProduct($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): static
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getProduct() === $this) {
                $picture->setProduct(null);
            }
        }

        return $this;
    }

    public function isPermanent(): ?bool
    {
        return $this->isPermanent;
    }

    public function setIsPermanent(?bool $isPermanent): static
    {
        $this->isPermanent = $isPermanent;

        return $this;
    }

    public function getProductGender(): ?string
    {
        return $this->productGender;
    }

    public function setProductGender(?string $productGender): static
    {
        $this->productGender = $productGender;

        return $this;
    }

    public function isDeleted(): ?bool
    {
        return $this->isDeleted;
    }

    public function setIsDeleted(bool $isDeleted): static
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }

    public function getOrderProducts(): Collection
    {
        return $this->orderProducts;
    }

    public function __toString(): string
    {
        return $this->getProductName();
    }

    public function getSize(): ?Size
    {
        return $this->size;
    }

    public function setSize(?Size $size): static
    {
        $this->size = $size;

        return $this;
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\SearchFormBeers;
use App\Model\SearchDataBeers;
use App\Form\SearchFormGoodies;
use App\Model\SearchDataGoodies;
use App\Service\VATpriceCalculator;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

final class ProductController extends AbstractController
{
   
    // DISPLAY ALL GOODIES + SEARCH
    #[Route('/product/goodies', name: 'app_goodies')]
    public function allGoodies(ProductRepository $productRepository, Request $request, VATpriceCalculator $VATpriceCalculator, Security $security): Response
    {   
        //AFFICHAGE DES PRODUITS 
        $idCategory = 2;
        $isDeleted = false;
        $products = $productRepository->findGoodies($idCategory,$isDeleted,[],['productName'=>'ASC']);
        //calcul prix TTC (pour l'affichage)
        foreach ($products as $product) {
            $VATprice = number_format($VATpriceCalculator->VATprice($product),2,'.','');
            $product->setProductVATprice($VATprice);
        }
        //FILTRE DE RECHERCHE 
        $searchData = new SearchDataGoodies(); //création d'une instance de la classe SearchDataBeers 
                                                //cette instance va contenir les critères de recherche 
        $form = $this->createForm(SearchFormGoodies::class,$searchData); //création d'un formulaire à partir de la classe SearchFormBeers
                                                                        //association du formulaire à l'objet searchData créé précédemment
        $form->handleRequest($request); //traitement de la requête HTTP => associe les données de la requête au formulaire

        if($form->isSubmitted() && $form->isValid()){ //si le formulaire est soumis et est valide
            $searchData->setCategory(2); //définition de la catégorie de produits concernés par la recherche 
                                        //en base de données, la catégorie "goodies" a l'identifiant 2
            $products = $productRepository->searchProductGoodie($searchData);//appelle de la méthode du repository pour lui passer les données de recherche
        }
        //FAVORIS 
        $user = $security->getUser(); // récupération de l'utilisateur en session
        $favorites = "";    // initialisation de la variables $favorites 
        if($user){  // si $user est définie
            $favorites = $user->getFavoriteProducts(); //récupére les produits favoris de l'utilisateur 
        }
        //rend la vue et passe les paramètres nécessaires, c'est à dire le formulaire 
        return $this->render('product/goodies.html.twig', [
            'products'=>$products,
            'form'=>$form,
            'favorites'=>$favorites,
            'meta_description'=>'Merchandising'
        ]);
    }

    
    // DISPLAY ALL BEERS + SEARCH 
    #[Route('/product/beers', name: 'app_beers')]
    #[Route('/product/beers/search', name:'app_beers_search')]
    public function allBeers(ProductRepository $productRepository, Request $request,VATpriceCalculator $VATpriceCalculator, Security $security): Response
    {   
        // j'indique l'id de la catégorie des bières 
        $idCategory=1;
        // je ne souhaite pas récupérer les produits "supprimés
        $isDeleted = false;
        // je récupère un tableau de produits non supprimés et appartenant à la catégorie des bières 
        // que j'ordonne selon leur nom dans l'ordre alphabétique 
        $products = $productRepository->findBeers($idCategory,$isDeleted,[],['productName'=>'ASC']);
        // pour chaque produit contenu dans le tableau de produits 
        foreach ($products as $product) {
            // je détermine leur prix TTC en faisant appel à la méthode VATprice() du service injecté
            $VATprice = number_format($VATpriceCalculator->VATprice($product),2,'.','');
            // j'affecte le prix TTC à l'objet produit 
            $product->setProductVATprice($VATprice);
        }

        $searchData = new SearchDataBeers();
        $form = $this->createForm(SearchFormBeers::class,$searchData);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $searchData->setCategory(1);
            $products = $productRepository->searchProductBeer($searchData);
        }

        $favorites="";
        $user = $security->getUser();
        if($user){
            $favorites = $user->getFavoriteProducts();
        }

        return $this->render('product/beers.html.twig', [
            'products'=>$products,
            'form'=>$form,
            'favorites'=>$favorites,
            'meta_description'=>'Nos bières'
        ]);
    }

    // DISPLAY A SPECIFIC PRODUCT
    #[Route('/product/{id}/detail', name: 'detail_product')]
    public function detailProduct(Product $product, ProductRepository $productRepository,VATpriceCalculator $VATpriceCalculator):Response
    {   
        $VATprice = number_format($VATpriceCalculator->VATprice($product),2,'.','');
        $product->setProductVATprice($VATprice);
        return $this->render('/product/detail-product.html.twig',[
            'product'=>$product,
            'VATprice' =>$VATprice,
            'meta_description'=>$product->getProductName()
        ]);
    }

    //ADD TO FAVORITES 
    #[Route('/favorite/add/{productId}',name:'add-to-favorites')]
    public function addFavorite(ProductRepository $productRepository,Security $security, int $productId,EntityManagerInterface $entityManager): JsonResponse
    {
        $product = $productRepository->find($productId);
        $user = $security->getUser();
        $product->addUser($user);
        $entityManager->persist($user);
        $entityManager->flush();

        return new JsonResponse(['success' => true,'productId'=>$productId]);
    }

    //REMOVE FROM FAVORITES
    #[Route('/favorite/remove/{productId}', name:'remove-from-favorites')]
    public function removeFromFavorites(Security $security, int $productId, ProductRepository $productRepository,EntityManagerInterface $entityManager){
        $user = $security->getUser();
        $product = $productRepository->find($productId);
        if($user && $product){
            $favorites = $user->getFavoriteProducts();
            if($favorites->contains($product)){
                $user->removeProduct($product);
                $entityManager->persist($user);
                $entityManager->flush();
            }
        return new JsonResponse(['success'=>true,'productId'=>$productId]);
        }
    }

}

templates/product/beers.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bières{% endblock %}



{% block body %}

 <div class="alertBox">
    <div class="alertContent">
        <p class="closeAlert"><i class="fa-solid fa-xmark"></i></p>
        <p class="alertMessage"></p>
    </div>
</div>

<a href="#header"><img class="top-button" src="/icones/arrow.webp" onclick="topFunction()" alt="Image représentant un cercle vert contenant une flèche blanche permettant de remonter en haut de page"></a>

<h1 id="beers-title">Nos bières</h1>

<div class="banner">
    <p>Nous n'effectuons pas de livraison : retirez vos produits au point de retrait de votre choix</p>
</div>

<div class="products__page-wrapper">
    <section class="products__sidebar">
        {{ form_start(form,{'attr': {'class': 'search-form'}}) }}
        <div class="sidebar-container">
            <h3> Par nom : </h3>
            {{ form_row(form.name) }}
        </div>   
        <div class="sidebar-container">
            <h3>par couleur : </h3>
            <div class="radio-button__container">
                {% for choice in form.color %}
                <div class="radio-button-group">
                    {{ form_widget(choice, {'attr': {'class': 'search-input'}}) }}
                    {{ form_label(choice, null, {'label_attr': {'class': 'search-label'}}) }}
                </div>
            {% endfor %}
            </div>
        </div>
        <div class="sidebar-container">
            <h3>par type : </h3>
            <div class="radio-button__container">
                {% for choice in form.type %}
                <div class="radio-button-group">
                    {{ form_widget(choice, {'attr': {'class': 'search-input'}}) }}
                    {{ form_label(choice, null, {'label_attr': {'class': 'search-label'}}) }}
                </div>
            {% endfor %}
            </div>
        </div> 
            <div class="sidebar-container">
                <h3>Gamme : </h3>
                <div class="radio-button__container">
                    {% for choice in form.isPermanent %}
                    <div class="radio-button-group">
                        {{ form_widget(choice, {'attr': {'class': 'search-input'}}) }}
                        {{ form_label(choice, null, {'label_attr': {'class': 'search-label'}}) }}
                    </div>
                    {% endfor %}
                </div>
            </div>
            {{ form_end(form) }}
        <a class="reset-button" href=" {{ path('app_beers') }} ">Reset</a>
    </section>

    <section class="products__container">
        {% if products %}
            {% for product in products %}
                <div class="product-card">
                    <div class="card-top">
                        <p class="beer-price">{{product.productVATprice}} €</p>
                        {% if app.user %}
                            {% if product in favorites %} <p class="add-to-favorites"><i class="fa-solid fa-heart" data-product-favorite="{{product.id}}"></p></i>
                            {% else %} <p class="add-to-favorites"><i class="fa-regular fa-heart" data-product-favorite="{{product.id}}"></i></p>
                            {% endif %}
                        {% endif %}
                    </div>
                    {% for picture in product.pictures %}
                        {% if loop.first %}
                        <div class="picture-container">
                            <a href="{{ path('detail_product',{id:product.id}) }}"><img src="{{ picture.pictureName }}" alt="photo de la face avant du produit {{product.productName}}"></a>
                        </div>
                        {% endif %}
                    {% endfor %}

                    <h3 class="centered">{{product.productName}}</h3> 
                    <p class="centered">{{product.type.typeName}} | {{product.productAlcoholLevel}} | {{product.productVolume}}</p>
                    <div class="stock-info" data-product="{{product.id}}" data-stock="{{product.productStock}}">{% if product.productStock > 10 %}<div class="green-dot"></div>en stock{% else %} <div class="red-dot"></div>indisponible{% endif %}</div>
                    <div class="wrapper">
                        <div class="quantity">
                            <button class="minus decrement" data-product="{{product.id}}" aria-label="Decrease">&minus;</button>
                            <input type="number" class="input-box qty-input" value="1" min="0" data-product="{{ product.id }}">
                            <button class="plus increment" data-product="{{product.id}}" aria-label="Increase">&plus;</button>
                        </div>
                    </div>
                <button class="btn basket-btn add-to-cart" data-product="{{product.id}}" type="submit">Ajouter au panier</button>
                </div>
            {% endfor %}
        {% else %}
            <p id="no-result">Aucun résultat</p>
        {% endif %}
    </section>
</div>

<script>
    function topFunction() {
        document.body.scrollTop = 0; // For Safari
        document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
      } 
</script>


{% endblock %}

templates/product/detail-product.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bières{% endblock %}

{% block body %}

<div class="alertBox">
    <div class="alertContent">
        <p class="closeAlert"><i class="fa-solid fa-xmark"></i></p>
        <p class="alertMessage"></p>
    </div>
</div>

<main class="detail-product-main">

        <section class="bezier-section">
            <div class="flip">
                {% for picture in product.pictures %}
                    {% if loop.first %}
                    <div class="front" style="background-image:url('{{ picture.pictureName}}')">
                    </div>
                    {% endif %}

                {% if loop.last %}
                    <div class="back" style="background-image:url('{{picture.pictureName}}')"></div>
                {% endif %}
                    
                {% endfor %}
            </div>
        </section>

        <section class="pricing-card-section">
            <div class="price-tag"><p>{{product.productVATPrice}} €</p></div>
            <h1 class="centered">{{product.productName}}</h1>
            {% if product.productStock > 10 %}
            <div class="stock-info stock-status available " data-product="{{product.id}}" data-stock="{{product.productStock}}">En stock</div>
        {% else %}
            <div class="stock-info stock-status unavailable " data-product="{{product.id}}" data-stock="{{product.productStock}}">Indisponible</div>
        {% endif %}
            
        <div class="description">
            <p id="product-description">{{product.productDescription}}</p>
            {% if product.productAlcoholLevel is not null %}
                <p class="row"><span>Volume d'alcool</span><span class="bold">{{product.productAlcoholLevel}}</span></p>
                {% else %}
                <p class="row"><span>Taille</span><span class="bold">{{product.size.sizeName}}</span></p>
            {% endif %}
            {% if product.productColor %}
                <p class="row"><span>Couleur</span><span class="bold">{{product.productColor}}</span></p>
            {% endif %}
            {% if product.type is not null %}
                <p class="row"><span>Type</span><span class="bold">{{product.type.typeName}}</span></p>
                {% else %}
                <p class="row"><span>Type</span><span class="bold">{{product.productGender}}</span></p>
            {% endif %}
            
        </div>
            
            <div class="qty-wrapper">
            <p>Quantité :</p>
                <div class="qty-container">
                    <button class="qty-btn-minus btn-rounded decrement" type="button" data-product="{{product.id}}"><i class="fa-solid fa-minus"></i></button>
                    <input type="text" name="qty" value="1" min="0" class="input-qty input-rounded qty-input" data-product="{{ product.id }}">
                    <button class="qty-btn-plus btn-rounded increment" type="button" data-product="{{product.id}}"><i class="fa-solid fa-plus"></i></button>
                </div>
            </div>

            <button data-product="{{product.id}}" type="submit"class="basket-btn-green btn add-to-cart">Ajouter au panier</button>

            <p id="success-message"></p>
        </section>
</main>

{% endblock %}

templates/product/goodies.html.twig
{% extends 'base.html.twig' %}

{% block title %}GOODIES{% endblock %}

{% block body %}

 <div class="alertBox">
    <div class="alertContent">
        <p class="closeAlert"><i class="fa-solid fa-xmark"></i></p>
        <p class="alertMessage"></p>
    </div>
</div>

<a href="#header"><img class="top-button" src="/icones/arrow.webp" alt=""></a>

<div class="banner">
    <p>Nous n'effectuons pas de livraison : retirez vos produits au point de retrait de votre choix</p>
</div>

<div class="products__page-wrapper">
    <section class="products__sidebar">
        {{ form_start(form,{'attr': {'class': 'search-form'}}) }}
        <div class="sidebar-container">
            <h3> Par article : </h3>
            {{ form_row(form.name) }}
        </div>   
        <div class="sidebar-container">
            <h3> Par couleur : </h3>
            <div class="radio-button__container">
                {% for choice in form.color %}
                <div class="radio-button-group">
                    {{ form_widget(choice, {'attr': {'class': 'search-input'}}) }}
                    {{ form_label(choice, null, {'label_attr': {'class': 'search-label'}}) }}
                </div>
            {% endfor %}
            </div>
        </div> 
        <div class="sidebar-container">
            <h3> Par genre : </h3>
            <div class="radio-button__container">
                {% for choice in form.productGender %}
                <div class="radio-button-group">
                    {{ form_widget(choice, {'attr': {'class': 'search-input'}}) }}
                    {{ form_label(choice, null, {'label_attr': {'class': 'search-label'}}) }}
                </div>
            {% endfor %}
            </div>
        </div> 
        <div class="sidebar-container">
            <h3>par taille: </h3>
            <div class="radio-button__container">
                {% for choice in form.size %}
                <div class="radio-button-group">
                    {{ form_widget(choice, {'attr': {'class': 'search-input'}}) }}
                    {{ form_label(choice, null, {'label_attr': {'class': 'search-label'}}) }}
                </div>
            {% endfor %}
            </div>
        </div> 
            {{ form_end(form) }}
        

        <a class="reset-button" href=" {{ path('app_goodies') }} ">Reset</a>
    </section>

    <section class="products__container">
        {% if products %}
            {% for product in products %}
                <div class="product-card">
                    {% if app.user %}
                        {% if product in favorites %}
                            <p class="add-to-favorites"><i class="fa-solid fa-heart" data-product-favorite="{{product.id}}"></p></i>
                        {% else %}
                            <p class="add-to-favorites"><i class="fa-regular fa-heart" data-product-favorite="{{product.id}}"></i></p>
                        {% endif %}
                    {% endif %}

                {% for picture in product.pictures %}
                    {% if loop.first %}
                        <a href="{{ path('detail_product',{id:product.id}) }}"><div class="picture-container"> <img src="{{ picture.pictureName }}" alt="photo de la face avant du produit"> </div></a>
                    {% endif %}
                {% endfor %}

                    <h3 class="centered">{{product.productName}}</h3> 
                    {% if product.productStock > 10 %}
                        <div class="stock-info" data-stock="{{product.productStock}}" data-product="{{product.id}}">
                            <div class="green-dot"></div>en stock
                        </div>
                    {% else %}
                        <div class="stock-info"><div class="red-dot"></div>indisponible</div>
                    {% endif %}
                        <p class="centered">{{product.productGender}}</p>
                        <p class="centered">{% if product.size is not null %}Taille {{product.size.sizeName}} - {% endif %}{{product.productColor}}</p>
                    

                            
                    
                    <p class="centered">{{product.productVATprice}} €</p>
                    <div class="wrapper">
                        <div class="quantity">
                            <button class="minus decrement" data-product="{{product.id}}" aria-label="Decrease">&minus;</button>
                                <input type="number" class="input-box" value="1" min="0" data-product="{{ product.id }}">
                            <button class="plus increment" data-product="{{product.id}}" aria-label="Increase">&plus;</button>
                        </div>
                    </div>
                <button class="btn basket-btn add-to-cart" data-product="{{product.id}}" type="submit">Ajouter au panier</button>
                </div>
            {% endfor %}
            {% else %}
            <p id="no-result">Aucun résultat</p>
        {% endif %}
    </section>
</div>

{% endblock %}