src/Entity/Establishment.php
<?php

namespace App\Entity;

use App\Repository\EstablishmentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EstablishmentRepository::class)]
class Establishment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $establishmentName = null;

    #[ORM\Column(length: 50)]
    private ?string $EstablishmentAddress = null;

    #[ORM\Column(length: 10)]
    private ?string $EstablishmentPostcode = null;

    #[ORM\Column(length: 50)]
    private ?string $establishmentCity = null;

    /**
     * @var Collection<int, Order>
     */
    #[ORM\OneToMany(targetEntity: Order::class, mappedBy: 'establishment')]
    private Collection $orders;

    /**
     * @var Collection<int, Schedule>
     */
    #[ORM\OneToMany(targetEntity: Schedule::class, mappedBy: 'establishment', orphanRemoval: true)]
    private Collection $schedules;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
        $this->schedules = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEstablishmentName(): ?string
    {
        return $this->establishmentName;
    }

    public function setEstablishmentName(string $establishmentName): static
    {
        $this->establishmentName = $establishmentName;

        return $this;
    }

    public function getEstablishmentAddress(): ?string
    {
        return $this->EstablishmentAddress;
    }

    public function setEstablishmentAddress(string $EstablishmentAddress): static
    {
        $this->EstablishmentAddress = $EstablishmentAddress;

        return $this;
    }

    public function getEstablishmentPostcode(): ?string
    {
        return $this->EstablishmentPostcode;
    }

    public function setEstablishmentPostcode(string $EstablishmentPostcode): static
    {
        $this->EstablishmentPostcode = $EstablishmentPostcode;

        return $this;
    }

    public function getEstablishmentCity(): ?string
    {
        return $this->establishmentCity;
    }

    public function setEstablishmentCity(string $establishmentCity): static
    {
        $this->establishmentCity = $establishmentCity;

        return $this;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    // public function addOrder(Order $order): static
    // {
    //     if (!$this->orders->contains($order)) {
    //         $this->orders->add($order);
    //         $order->setEstablishment($this);
    //     }

    //     return $this;
    // }

    public function removeOrder(Order $order): static
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getEstablishment() === $this) {
                $order->setEstablishment(null);
            }
        }

        return $this;
    }


    public function __toString()
    {
        return $this->establishmentName;
    }

    /**
     * @return Collection<int, Schedule>
     */
    public function getSchedules(): Collection
    {
        return $this->schedules;
    }

    public function addSchedule(Schedule $schedule): static
    {
        if (!$this->schedules->contains($schedule)) {
            $this->schedules->add($schedule);
            $schedule->setEstablishment($this);
        }

        return $this;
    }

    public function removeSchedule(Schedule $schedule): static
    {
        if ($this->schedules->removeElement($schedule)) {
            // set the owning side to null (unless already changed)
            if ($schedule->getEstablishment() === $this) {
                $schedule->setEstablishment(null);
            }
        }

        return $this;
    }
}

src/Controller/PaymentController.php
<?php

namespace App\Controller;

use Dompdf\Dompdf;
use Stripe\Stripe;
use Dompdf\Options;
use App\Entity\Bill;
use App\Entity\Order;
use App\Service\Mailer;
use App\Entity\OrderProduct;
use Stripe\Checkout\Session;
use App\Entity\Establishment;
use App\Form\PickUpPointFormType;
use App\Repository\OrderRepository;
use App\Service\VATpriceCalculator;
use App\Form\IdentificationFormType;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\EstablishmentRepository;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class PaymentController extends AbstractController
{
      #[Route('/payment/identification', name:'app_payment-identification')]
    public function identification(Request $request, SessionInterface $session): Response
    {   
        // création du formulaire 
        $identificationForm = $this->createForm(IdentificationFormType::class);
        // traitement de la requête
        $identificationForm->handleRequest($request); 
        // si formulaire soumis et valide
        if ($identificationForm->isSubmitted() && $identificationForm->isValid()) {
            //récupération des données du formulaire
            $data = $identificationForm->getData();
            //enregistrement en session
            $session->set('identificationData',$data);
            // redirection vers la page choisir point de retrait
            // dd($session);
            return $this->redirectToRoute('app_payment-pickUpPoint');
        }

        return $this->render('/payment/identification.html.twig',[
            'identificationForm' => $identificationForm,
            'meta_description' => "Vous êtes à l'étape 1/3 du paiement. Dites-nous qui vous êtes pour que nous puissions préparer votre commande"
        ]);
    }

    #[Route('/payment/pickUpPoint', name:'app_payment-pickUpPoint')]
    public function pickUpPoint(EstablishmentRepository $establishmentRepository, Request $request, SessionInterface $session): Response
    {   
        // récupérer les établissement en bdd pour les envoyer à la vue 
        $establishments = $establishmentRepository->findAll([],['establishmentName'=>'ASC']);
        // créer le formulaire permettant de connaître le choix de l'utilisateur
        $pickUpPointForm = $this->createForm(PickUpPointFormType::class);
        //traitement de la requête envoyée par le client via le formulaire
        $pickUpPointForm->handleRequest($request);
        //si le formulaire est soumis et valide
        if ($pickUpPointForm->isSubmitted() && $pickUpPointForm->isValid()){
            // j'extraie les data du formulaire (le formulaire contient un array avec "establishmentName" => "2") et les stocke dans une variable
            // en récupérant seulement l'id (la valeur associée à la clé), getData() récupère l'objet lié ; 
            // sinon on enregistre un tableau avec la clé establishmentName avec l'objet pour valeur
            $establishment = $pickUpPointForm->get('establishmentName')->getData();
            // j'enregistre l'objet contenu dans $establishment en session 
            $session->set('establishment',$establishment);


            // redirection vers la page paiement de Stripe 
            return $this->redirectToRoute('app_payment-recap');
        }

        return $this->render('/payment/pickUpPoint.html.twig', [
            'establishments' => $establishments,
            'pickUpPointForm' => $pickUpPointForm,
            'meta_description' => "Vous êtes à l'étape 2/3 du paiement. Choisissez le point de retrait où vous souhaitez retirer votre commande"
        ]);
    }

    #[Route('/payment/recap', name:'app_payment-recap')]
    public function recap(SessionInterface $session, ProductRepository $productRepository, VATpriceCalculator $priceCalculator):Response
    {  
        $cart = $session->get('cart');
        $products = [];
        $nbItems = 0;
        $total = 0;
        $subTotals=[];
        $quantities = [];
        
        //pour chaque élément du tableau associatif $cart 
        foreach ($cart as $id=> $quantity) {
            // je récupère le prodiut à partir de l'id 
            $product = $productRepository->find($id);
            // calcul du sous-total
            $subTotal = number_format($priceCalculator->vatPriceSubTotal($product,$quantity),2,'.',' ');
            // j'ajoute le sous-total à un tableau associatif $id => $subTotal 
            $subTotals[$product->getId()] = $subTotal;
            // j'additionne les quantités pour obtenir le nombre total de produits 
            $nbItems += $quantity;
            // j'additionne les sous-totaux pour obtenir le total
            $total+=$subTotal;
            $totalformatted = number_format($total,2,'.',' ');
            // j'ajoute le total en session 
            $session->set('total',$totalformatted);
            // j'ajoute le produit à un tableau associatif indexé pour pouvoir les encoyer à la vue et les y afficher à l'aide d'une boucle
            $products[]=$product;
            // j'ajoute la quantité associée à chaque produit à un tableau associatif avec l'id produit comme index pour pouvoir récupérer la quantité associée au produit dans la vue
            $quantities[$product->getId()] = $quantity;
        }

        return $this->render('/payment/recap.html.twig', [
            'products' => $products,
            'total' => $totalformatted,
            'nbItems' => $nbItems,
            'subTotals' => $subTotals,
            'quantities' => $quantities,
            'meta_description' => "Récapitulatif de votre commande"
        ]);
    }

    
    #[Route('/payment/checkout', name:'app_payment-checkout')]
    public function checkout(SessionInterface $session, ProductRepository $productRepository,
    VATpriceCalculator $priceCalculator)
    {   
        $cart = $session->get('cart'); // récupération du panier enregistré en session 
        $total = $session->get('total'); // récupération du total TTC enregisté en session 
        $identificationData = $session->get('identificationData'); // récupération des données utilisateurs 
        $userEmail = $identificationData['orderEmail']; // récupération de l'email à partir des données utilisateurs
        
        // configuration de la clé secrète pour l'API qui permet d'effectuer les paiements
        // la clé est récupérée dans la variable d'environnement définie dans .env
        Stripe::setApiKey($_ENV['STRIPE_SECRET_KEY']);
        // définition de l'URL du domaine utilisé pour redirections après paiement 
        $YOUR_DOMAIN = 'http://127.0.0.1:8000';

        $checkout_session = Session::create([ //création session Checkout
            'payment_method_types' => ['card'], //définition méthodes de paiement autorisés (cb uniquement)
            'line_items' => [ //définition des articles de la commande : ici un seul article représente l'ensemble
            // du panier pour plus de simplicité 
                [
                    'price_data' => [ //définition de la devise utilisée pour le paiement
                        'currency' => 'eur', //paiement en euros
                        'product_data' => [
                            'name' => 'Commande',  // nom générique de la commande
                        ],
                        'unit_amount' => $total * 100,  // montant total de la commande
                        // le montant total est multiplié par 100 car doit être exprimé en centimes
                    ],
                    'quantity' => 1,  // quantité de l'article
                    // ici quantité de 1 car la commande est représenté par un seul article
                ],
            ],
            'customer_email'=> $userEmail, //email de l'utilisateur pour préremplir champ email de la page de paiement
            'mode' => 'payment', //paiement unique 
            'success_url' => $YOUR_DOMAIN . '/payment/checkout/success', //URL de la page de succès 
            'cancel_url' => $YOUR_DOMAIN . '/payment/checkout/cancel', //URL de la page d'échec
            ]);
            //une fois la session de paiement créée avec Stripe,
            // l'utilisateur est redirigé vers la page de paiement Stripe
            // la méthode 'url' de la session Stripe contient l'URL où l'utilisateur peut compléter le paiement.
            return new RedirectResponse($checkout_session->url);
        }

        #[Route('/payment/checkout/success', name:'app_payment-checkout-success')]
        public function success(EstablishmentRepository $establishmentRepository, SessionInterface $session, Security $security, EntityManagerInterface $entityManager, ProductRepository $productRepository, VATPriceCalculator $priceCalculator):Response
        {   
            //**************************COMMANDE
            //création d'un nouvel objet commande 
            $order = new Order;
            //AJOUT DATE 
            $order->setDateOfPlacement(new \DateTime());
            //AJOUT REFERENCE
            $order->setOrderReference(uniqid('stecru-e'));
            //AJOUT COORDONNES 
            // récupération du tableau de données d'identification en session
            $identificationData = $session->get('identificationData');
            // récupération de la clé prénom utilisateur et de sa valeur
            $orderFirstName = $identificationData['orderUserFirstName'];
            // ajout prénom utilisateur (clé + valeur)
            $order->setOrderUserFirstName($orderFirstName);
            // idem avec nom de famille et email
            $orderLastName = $identificationData['orderUserLastName'];

templates/payment/bill.html.twig
<h1 class="wide centered">SAS {{seller.establishmentName}}</h1>
<p class="centered">{{seller.establishmentAddress}}<br>
{{seller.establishmentPostCode}} {{seller.establishmentCity}}<br>
siret:	751 460 742 00024</p>
<div class="horizontal-line"></div>

<p class="centered"> <span class="wide bold">Merci {{order.orderUserFirstName}},</span>
<p class="grey"><span class="bold">Votre commande du {{order.dateOfPlacement|date('d.m.Y')}}</span> est bien enregistrée sous la référence <span class="bold">{{order.orderReference}}.</span></p>
<p class="grey">Votre commande sera disponible à partir du {{pickUpTime|date('d.m.Y')}} aux horaires d'ouverture du point de retrait que vous avez sélectionné.</p>
<p class="grey">Pour la retirer, munissez-vous d'une pièce d'identité et de votre numéro de commande.</p>
<p class="grey">Nous vous rappelons que vous avez choisi de retirer votre commande à :</p> <p class="pickUpPoint">{{order.establishment.establishmentName}}<br>{{order.establishment.establishmentAddress}}<br>{{order.establishment.establishmentPostCode}} {{order.establishment.establishmentCity}}</p>
<p class="grey">Pour consulter les horaires d'ouverture de nos points de retrait, rendez-vous sur notre site et cliquez sur le lien 'horaires d'ouverture' visible en pied de page</p>

<h2>Votre commande</h2>
<table class="bill-table">
    <th>
        <tr>
        <th class="left">Désignation produit</th>
        <th class="centered">Prix unitaire HT</th>
        <th class="centered">Quantité</th>
        <th class="centered">TVA</th>
        <th class="right">Sous-total TTC</th>
        </tr>
    </th>
    <tbody>

        {% for orderProduct in order.orderProducts %}

        <tr>
            <td class="grey capitalize">{{orderProduct.appProduct.productName}} - 
                {% if orderProduct.appProduct.productVolume is not null %}
                    {{orderProduct.appProduct.productVolume}}
                {% else %}
                    {{orderProduct.appProduct.size.sizeName}}
                {% endif %}
            </td> -
            <td class="centered grey">
                {{orderProduct.appProduct.productPrice}} €
            </td>
            <td class="centered grey">{{orderProduct.quantity}}</td>
            <td class="centered">{{orderProduct.appProduct.vat.vatRate * 100}} %</td>
            <td class="right grey"> {{subTotals[orderProduct.appProduct.id]}} €</td>
        </tr>
        {% endfor %}
  

<tr class="total"><td class="bold centered">TOTAL TTC</td><td class="centered">-</td><td class="bold centered">{{nbItems}} articles</td><td></td><td class="bold right">{{order.orderTotal}} €</td></tr>
</tbody>
</table>

<h2>Paiement</h2>
<p><span class="bold">Total T.T.C :</span> {{order.orderTotal}} €</p>
<p><span class="bold">Total H.T :</span> {{totalNoVat}} €</p>
<p><span class="bold">TVA :</span> {{formattedVat}} €</p>
<p><span class="bold">Mode de paiement :</span> carte bancaire</p>


<style>


*{
    font-family:'helvetica';
}
h1{
    font-size: 1.5em !important;
}
h2{
    margin-top:3rem;
}
.bill-table{
    margin:2rem 0 2rem 0;
    width:100%;
    border-collapse: collapse;
    
}

.bill-table tr{
    width:100%;

}

.bill-table td{
    padding:10px 5px 10px 5px;
    font-size:0.9em;
}

.bold{
    font-weight:700;
}
.centered{
    text-align: center;
}

.total{
    border-top:1px solid grey;
}

.left{
    text-align: left;
}

.right{
    text-align: right;
}

.wide{
    font-size:1.3em;
}

.half-wide{
    font-size:1.5em;
}

.pickUpPoint{
    width:25%;
    margin:auto;
    border-radius:3px;
    padding:0.3rem;
    border:solid 2px rgb(57, 120, 57);
    text-align: center;
    font-weight: 700;
}

.grey{
    color:rgb(71, 71, 71);
}

.horizontal-line{
    width: 100%;
    height:2px;
    background-color: rgb(215, 215, 215);
    border-radius: 50px;
}

.capitalize{
    text-transform: capitalize;
}


</style>

templates/payment/cancel.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paiement annulé{% endblock %}

{% block body %}

<div class="cancel-page__wrapper">
    <p class="centered oops">oups, quelque chose s'est mal passé</p>
    <div class="cancel-container">
        <img src="/icones/cancel.webp" alt="Icône représent un rond ayant un fond rouge et une croix blanche"> 
        <p>Paiement annulé</p>
    </div>
    <p class="centered try-again">Veuillez réessayer</p>
    <a class="basket-btn">Retourner au panier <i class="fa-solid fa-circle-arrow-right"></i></a>
  
</div>




{% endblock %}

templates/payment/collection.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paiement étape 2/3{% endblock %}

{% block body %}

<main class="collection-page">
            
    <h1>2. Choisissez votre point de retrait</h1>

    <div class="horizontal-line"></div>

        {{ form_errors(collectionForm) }}
                {{ form_start(collectionForm,{'attr': {'class': ''}}) }}
                <div class="options-container">
                {% for establishment in establishments %}
                    <section class="option-container">
                        <h2>{{establishment.establishmentName}}</h2>
                        <h3>Adresse</h3> 
                        <p> {{establishment.establishmentAddress}} - {{establishment.establishmentPostCode}} {{establishment.establishmentCity}}</p>
                        <a href="">Voir sur la carte <i class="fa-solid fa-location-arrow"></i></a>
                        <h3>Horaires d'ouverture</h3>
                        <table>
                        </table>
                    </section>
                {% endfor %}
                </div>
            <button class="btn choose-btn" type="submit" name="submit">Continuer</button>
        {{ form_end(collectionForm) }}
    </div>
</main>
                
          
                    {# <table>
                        <thead>
                            <tr>
                            <th>Jour</th>
                            <th>Matin</th>
                            <th>Après-midi</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="colored"><td>lundi</td><td></td><td class="closed">fermé</td></tr>
                            <tr><td>mardi</td><td></td> <td>17h - 22h30</td></tr>
                            <tr class="colored"><td>mercredi</td><td></td><td>17h - 22h30</td></tr>
                            <tr><td>jeudi</td><td></td><td>17h - 22h30</td></tr>
                            <tr class="colored"><td>vendredi</td><td></td><td> 17h - 22h30</td></tr>
                            <tr><td>samedi</td> <td>10h-20h</td><td>15h - 20h30</td></tr>
                            <tr class="colored"><td>dimanche<td></td></td><td class="closed">fermé</td></tr>
                        </tbody>
                    </table> #}





{% endblock %}

templates/payment/identification.html.twig
{% extends 'base.html.twig' %}

{% block title %}Identifiez-vous{% endblock %}

{% block body %}
   
        <section class="identification-page">
            
            <h2>Etape 1: Vos coordonnées</h2>

            <div class="horizontal-line"></div>

                {{ form_start(identificationForm,{'attr': {'class': 'identification-form'}}) }}
                    <div class="groups-wrapper">
                        <div class="identificationForm-group">
                            {{form_label(identificationForm, 'Prénom',{'label_attr':{'class':'id-label'}})}}
                            {{form_widget(identificationForm.orderUserFirstName) }}
                        </div>
                        <div class="identificationForm-group">
                            {{form_label(identificationForm, 'Nom',{'label_attr':{'class':'id-label'}})}}
                            {{form_widget(identificationForm.orderUserLastName) }}
                        </div>
                    </div>
                    <div class="identificationForm-group">
                        {{form_label(identificationForm, 'Email',{'label_attr':{'class':'id-label'}})}}
                        {{form_widget(identificationForm.orderEmail, {'attr': {'value':app.user ? app.user.getEmail() : ''} }) }}
                        {{ form_errors(identificationForm.orderEmail) }}
                    </div>
                    <div class="groups-wrapper">
                        <div class="agreeTerms-group">
                            {{form_label(identificationForm, 'Je certifie avoir 18 ans',{'label_attr':{'class':'id-label'}}) }}
                            {{form_widget(identificationForm.agreeTerms) }}
                        </div>
                        <p>Un justificatif d'identité vous sera demandé lors du retrait</p>
                    </div>
                    
                    <a href="app_payment-identification"><button type="submit" class="identification-btn btn">Continuer</button></a>
                    
                {{ form_end(identificationForm) }}

        </section>



{% endblock %}

templates/payment/pickUpPoint.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paiement étape 2/3{% endblock %}

{% block body %}

<main class="pickUpPage-page">
            
    <h1>2. Choisissez votre point de retrait</h1>

    <div class="horizontal-line"></div>
         
    <div class="options-container">
        {% for establishment in establishments %}
            <section class="option-container">
                <h2>{{establishment.establishmentName}}</h2>
                <h3>Adresse</h3> 
                <p> {{establishment.establishmentAddress}} - {{establishment.establishmentPostCode}} {{establishment.establishmentCity}}</p>
                <a class="map-button" href="" id="{{establishment.id}}" >Voir sur la carte <i class="fa-solid fa-location-arrow"></i></a>
                <h3>Horaires d'ouverture</h3>
                <table>
                    <thead>
                        <tr>
                        <th>Jour</th>
                        <th>Matin</th>
                        <th>Après-midi</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="colored"><td>lundi</td><td></td><td class="closed">fermé</td></tr>
                        <tr><td>mardi</td><td></td> <td>17h - 22h30</td></tr>
                        <tr class="colored"><td>mercredi</td><td></td><td>17h - 22h30</td></tr>
                        <tr><td>jeudi</td><td></td><td>17h - 22h30</td></tr>
                        <tr class="colored"><td>vendredi</td><td></td><td> 17h - 22h30</td></tr>
                        <tr><td>samedi</td> <td>10h-20h</td><td>15h - 20h30</td></tr>
                        <tr class="colored"><td>dimanche<td></td></td><td class="closed">fermé</td></tr>
                    </tbody>
                </table>
            </section>
        {% endfor %}
    </div>

    <h4 class="centered">Indiquez votre choix : </h4>
    {{ form_start(pickUpPointForm) }}
        {{form_widget(pickUpPointForm)}}
        {{ form_errors(pickUpPointForm) }}
        <button class="btn choose-btn" type="submit" name="submit">Valider</button>
    {{ form_end(pickUpPointForm) }}

</main>
                
        

<style>
    .iframe-container{
        width:40%;
        margin:auto;
        display:none;
    }

    #pick_up_point_form_establishmentName{
        display:flex;
        justify-content:center;
        margin:2rem;
    }

    #pick_up_point_form_establishmentName input{
        margin : 0.5rem;
    }

    #pick_up_point_form_establishmentName label{
        font-size:2em;
    }

    .pickUpPage-page h4{
        font-size:2em;
        font-family:'Nunito';
    }
       
</style>




{% endblock %}

templates/payment/recap.html.twig
{% extends 'base.html.twig' %}

{% block title %}Récapitulatif de votre commande{% endblock %}

{% block body %}
<h1 class=centered>Récapitulatif avant paiement</h1>
<div class="recap-wrapper">
    <table id="recap-table">
        <thead>
            <tr>
                <th>Produit</th>
                <th>Quantité</th>
                <th>Prix</th>
            </tr>
        </thead>
        <tbody>
        {% for product in products %}
            
            <tr class="recap-item-row">
                <td>
                {% for picture in product.pictures %}
                    {% if loop.first %}
                        <img class="recap-picture" src="{{picture.pictureName}}" alt="photo de la face avant du produit">
                    {% endif %}
                {% endfor %}
                {{product.productName}} - {% if product.productVolume is not null %}{{product.productVolume}}{% else %}{{product.size.sizeName}}{% endif %}
                </td>
                <td>{{quantities[product.id]}}</td>
                <td>{{subTotals[product.id]}} €</td>
            </tr>
        {% endfor %}
            <tr>
                <td></td><td class="total-recap">TOTAL TTC :</td><td class="bold large total-recap-amount">{{total}} €</td>
            </tr>
        </tbody>
    </table>
    <a class="btn choose-btn" href="{{ path('app_payment-checkout') }}">Payer</a>
</div>



{% endblock %}

templates/payment/success.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paiement réussi{% endblock %}

{% block body %}

<div class="sucess-page__wrapper">
    <p class="centered thanks">Merci pour votre commande !</p>
    <div class="success-container">
        <img src="/icones/success120.webp" alt="Icône représent un rond ayant un fond vert et une coche blanche"> 
        <p>Paiement réussi</p>
    </div>
    <p class="centered confirmed">Un e-mail de confirmation vous a été envoyé</p>
    <a href="{{path('app_payment-checkout-bill')}} " target="_blank" class="confirmed">Cliquez <span class="bold">ici</span> pour visualiser la <span class="bold">confirmation de commande </span>dans le navigateur</a>
</div>

{% endblock %}